data:
  img_size: 224
  k_fold: 'No'
  name: lisc
  save_folder: checkpoints/lisc
  supervised_ratio: 0.25
  test_folder: processed_data/lisc/
  train_aug: true
  train_folder: processed_data/lisc/
  val_folder: processed_data/lisc/
debug: false
device: cuda
fold: 1
log: false
model_adapt:
  adapt_method: false
  num_domains: false
model_encoder_id: 0
seed: 1
semi:
  conf_thresh: 0.8
swin:
  DEPTHS:
  - 2
  - 2
  - 18
  DROP_PATH_RATE: 0.2
  EMBED_DIM: 192
  NUM_HEADS:
  - 6
  - 12
  - 24
  WINDOW_SIZE: 7
  name: swin_large_patch4_window7_224_22k
test:
  batch_size: 5
  num_workers: 0
  only_test: false
  test_model_dir: ''
train:
  l_batchsize: 8
  num_epochs: 80
  num_iters: false
  num_workers: 0
  optimizer:
    adam:
      betas:
      - 0.9
      - 0.999
      lr: 1e-4
    adamw:
      betas:
      - 0.9
      - 0.999
      eps: 1e-8
      lr: 1e-4
      weight_decay: 0.05
    mode: adamw
  u_batchsize: 8
